name: GitHub Actions CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Dotfiles
        run: |
          ./install

      - name: Check Homebrew installation
        run: which brew

      - name: Check tree installation
        run: which tree
